version: "1"
rules:
  - base: swiftwasm
    upstream: apple:master
    mergeMethod: hardreset
    assignees:
      - kateinoigakukun
  - base: katei/swiftwasm
    upstream: swiftwasm
    mergeMethod: merge
    assignees:
      - kateinoigakukun
label: ":arrow_heading_down: Upstream Tracking"
