jobs:
- job: Build
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      sudo apt update
      sudo apt install \
        git cmake ninja-build clang python \
        uuid-dev libicu-dev icu-devtools libbsd-dev \
        libedit-dev libxml2-dev libsqlite3-dev swig \
        libpython-dev libncurses5-dev pkg-config \
        libblocksruntime-dev libcurl4-openssl-dev \
        systemtap-sdt-dev tzdata rsync
    displayName: Install dependencies via apt-get
  - script: |
      mkdir swift-source
    displayName: Create swift-source workspace
  - checkout: self
    path: swift-source/swift
  - script: |
      wget -O wasisdk.deb "https://github.com/swiftwasm/wasi-sdk/releases/download/20190421.6/wasi-sdk_3.19gefb17cb478f9.m_amd64.deb"
      sudo dpkg -i wasisdk.deb
      wget -O icu.tar.xz "https://github.com/swiftwasm/icu4c-wasi/releases/download/20190421.3/icu4c-wasi.tar.xz"
      tar xf icu.tar.xz
    workingDirectory: swift-source
    displayName: Install wasi-sdk and icu4c-wasi
  - script: |
      sourcedir="$PWD"
      cd swift
      utils/build-script --debug --wasm \
        --llvm-targets-to-build "X86;WebAssembly" \
        --wasm-wasi-sdk "/opt/wasi-sdk" \
        --wasm-icu-uc "todo" \
        --wasm-icu-uc-include "$sourcedir/icu_out/include" \
        --wasm-icu-i18n "todo" \
        --wasm-icu-i18n-include "todo" \
        --wasm-icu-data "todo" \
        --build-swift-static-stdlib \
        --install-swift \
        --install-prefix="/opt/swiftwasm-sdk" \
        --install-destdir="$sourcedir/install" \
        --installable-package="$sourcedir/swiftwasm.tar.gz"
        cp "$sourcedir/swiftwasm.tar.gz" "$BUILD_ARTIFACTSTAGINGDIRECTORY/"
    displayName: Build swiftc
    timeoutInMinutes: 0
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: swiftwasm-sdk
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github-release
      tagSource: manual
      tag: $(Build.BuildNumber)
      assets: |
        $(Build.ArtifactStagingDirectory)/*
