name: CI

on:
  push:
    branches:
    - swiftwasm
  pull_request:
    branches:
    - swiftwasm

jobs:
  linux_build:
    timeout-minutes: 0
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build Linux installable archive
      run: ./ci-linux.sh
    - name: Upload Linux installable archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-installable
        path: ../swiftwasm-linux.tar.gz

  macos_build:
    timeout-minutes: 0
    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Build macOS installable archive
      run: ./ci-mac.sh
    - name: Upload macOS installable archive
      uses: actions/upload-artifact@v1
      with:
        name: macos-installable
        path: ../swiftwasm-mac.tar.gz

  package:
    name: Build SwiftWasm packages
    needs:
    - linux_build
    - macos_build
    runs-on: ubuntu-18.04
    steps:
      - name: Download installable Linux archive
        uses: actions/download-artifact@v1
        with:
          name: linux-installable
      - name: Download installable macOS archive
        uses: actions/download-artifact@v1
        with:
          name: macos-installable
      - name: Build the packages
        shell: bash
        run: |
          git clone https://github.com/swiftwasm/swiftwasm-package-sdk.git
          cd swiftwasm-package-sdk
          ./download-prebuilts.sh

          cp ../linux-installable/swiftwasm-linux.tar.gz prebuilt/swiftwasm.tar.gz
          cp ../macos-installable/swiftwasm-mac.tar.gz prebuilt/swiftwasm-mac.tar.gz
          ./build-packages.sh

          cd output
          tar xf swiftwasm-sdk-linux.tar.xz

          cd swiftwasm-sdk
          ./swiftwasm example/hello.swift hello.wasm
